markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks
author:
    name: Lai Yiu Ming
title: Droid G2 - Gnutella 2 client on Android
tagline: Droid G2 - Gnutella 2 client on Android
author:
    name: Toxic-lab (HK)
    email: kongutoxiclab@gmail.com
    github: toxic-lab
production_url : http://toxic-lab.github.io
ads:
    google: false
permalink: short-urls-jekyll 